name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23

    steps:
    - uses: actions/checkout@v3

    - name: Install GnuGo
      run: sudo apt install gnugo

    - name: Compile
      run: rebar3 compile

    - name: Dialyzer
      run: rebar3 dialyzer

    - name: Run tests
      run: rebar3 do eunit, ct
